### ISSUE TITLE
Does not work with http proxy

### ISSUE THREAD

**Issue by pbakondy** [aboros/hubot-napirajz#1]
Tested on macOS 10.12.3

```
hubot> hubot napi delfines
hubot> [Fri Feb 10 2017 20:05:55 GMT+0100 (CET)] ERROR TypeError: Cannot read property 'statusCode' of null
  at /Users/pbakondy/dev/hubot/node_modules/hubot-napirajz/src/napirajz.coffee:25:9, <js>:11:20
  at ClientRequest.<anonymous> (/Users/pbakondy/dev/hubot/node_modules/scoped-http-client/src/index.js:99:20)
  at emitOne (events.js:96:13)
  at ClientRequest.emit (events.js:188:7)
  at Socket.socketErrorListener (_http_client.js:309:9)
  at emitOne (events.js:96:13)
  at Socket.emit (events.js:188:7)
  at emitErrorNT (net.js:1281:8)
  at _combinedTickCallback (internal/process/next_tick.js:74:11)
  at process._tickCallback (internal/process/next_tick.js:98:9)

[Fri Feb 10 2017 20:05:55 GMT+0100 (CET)] ERROR TypeError: Cannot read property 'statusCode' of null
  at /Users/pbakondy/dev/hubot/node_modules/hubot-napirajz/src/napirajz.coffee:25:9, <js>:11:20
  at ClientRequest.<anonymous> (/Users/pbakondy/dev/hubot/node_modules/scoped-http-client/src/index.js:99:20)
  at emitOne (events.js:96:13)
  at ClientRequest.emit (events.js:188:7)
  at Socket.socketCloseListener (_http_client.js:285:9)
  at emitOne (events.js:101:20)
  at Socket.emit (events.js:188:7)
  at TCP._handle.close [as _onclose] (net.js:501:12)



hubot> exit

iMac:hubot pbakondy$ echo $http_proxy
http://192.168.150.11:8080/
```

**Comment by aboros** [comment]
it seems to me this is a common problem with running hubot behind a proxy. in similar issues for other scripts making .get() calls i found this hubot script as recommended: https://www.npmjs.com/package/hubot-proxy-loader
adding this to your hubot will probably resolve the issue.

i will add a check for the `resp` anyways, thanks for the report.
